homeassistant: !include config/homeassistant.yaml

frontend:
  themes: !include_dir_merge_named themes

config:
system_health:
#discovery:
history:
logbook:
mobile_app:
luftdaten:
  sensor_id: 21229
  show_on_map: true
  sensors:
    monitored_conditions:
      - P1
      - P2


lovelace:
  mode: yaml

http: !include config/http.yaml
fan: !include config/fan.yaml
tplink: !include config/tplink.yaml

sensor: !include config/sensor.yaml
switch: !include config/switch.yaml
input_number: !include config/input_number.yaml
input_select: !include config/input_select.yaml
automation: !include config/automation.yaml
