homeassistant: !include config/homeassistant.yaml

frontend:
  themes: !include_dir_merge_named themes

config:
system_health:
#discovery:
history:
logbook:
mobile_app:
luftdaten:
  sensor_id: 21229
  show_on_map: true
  sensors:
    monitored_conditions:
      - P1
      - P2


lovelace:
  mode: yaml

http:
  server_port: 8123
  ssl_certificate: /config/ssl/fullchain.pem
  ssl_key: /config/ssl/privkey.pem
  base_url: mi-air-pure-1
  ip_ban_enabled: False

fan:
  - platform: xiaomi_miio
    host: "10.100.101.97"
    token: !env_var mi_1_token
    name: "xiaomi.air.purifier.2s.1" # fan.xiaomi_air_purifier_2s_1
    model: zhimi.airpurifier.mc1

tplink: !include config/tplink.yaml

sensor: !include config/sensor.yaml

switch: !include config/switch.yaml

input_number: !include config/input_number.yaml

input_select: !include config/input_select.yaml

automation: !include config/automation.yaml
