homeassistant: !include config/homeassistant.yaml

frontend: !include config/frontend.yaml

config:
system_health:
#discovery:
#mobile_app:
history:
logbook:
joaoapps_join:
  api_key: !env_var join_api_key
  device_id: !env_var join_device_id

lovelace:
  mode: yaml

luftdaten: !include config/luftdaten.yaml
http: !include config/http.yaml
fan: !include config/fan.yaml
tplink: !include config/tplink.yaml
notify: !include config/notify.yaml
mikrotik: !include config/mikrotik.yaml

sensor: !include config/sensor.yaml
switch: !include config/switch.yaml
input_number: !include config/input_number.yaml
input_select: !include config/input_select.yaml
automation: !include config/automation.yaml
