homeassistant: !include config/homeassistant.yaml

frontend:
  themes: !include_dir_merge_named themes

config:
system_health:
#discovery:
#mobile_app:
history:
logbook:

lovelace:
  mode: yaml

luftdaten: !include config/luftdaten.yaml
http: !include config/http.yaml
fan: !include config/fan.yaml
tplink: !include config/tplink.yaml

sensor: !include config/sensor.yaml
switch: !include config/switch.yaml
input_number: !include config/input_number.yaml
input_select: !include config/input_select.yaml
automation: !include config/automation.yaml
