title: Zetxx Home Automation
views:
  - title: Air Purifiers
    theme: dark-mode
    panel: true
    cards:
      - title: Rooms
        type: vertical-stack
        cards:
          - title: Bedroom
            type: horizontal-stack
            cards:
              - title: State
                type: entities
                entities:
                  - input_number.mi_1_input_number_favorite_level
                  - input_select.mi_1_input_select_mode
                  - sensor.mi_1_sensor_aqi
                  - sensor.mi_1_sensor_speed
                  - sensor.mi_1_sensor_filter_remaining
                  - sensor.mi_1_sensor_humidity
                  - sensor.mi_1_sensor_temperature
                  - switch.mi_1_switch_buzzer
                  - switch.mi_1_switch_child_lock
                  - switch.mi_1_switch_led
                show_header_toggle: false
                theme: default
              - title: History
                entities:
                  - sensor.mi_1_sensor_aqi
                  - sensor.luftdaten_21229_p2
                  - sensor.mi_1_sensor_speed
                  - sensor.mi_1_sensor_filter_remaining
                  - sensor.mi_1_sensor_mode
                  - sensor.mi_1_sensor_humidity
                  - sensor.mi_1_sensor_temperature
                show_header_toggle: false
                hours_to_show: 80
                refresh_interval: 60
                type: history-graph
  - title: Switches
    theme: dark-mode
    panel: true
    cards:
      - title: Rooms
        type: vertical-stack
        cards:
          - title: Livingroom
            type: horizontal-stack
            cards:
              - title: State
                type: entities
                entities:
                  - sensor.plug1_today_energy_kwh
                  - sensor.plug1_total_energy_kwh
                  - sensor.plug1_voltage
                show_header_toggle: false
                theme: default
              - title: History
                entities:
                    - sensor.plug1_voltage
                    - sensor.plug1_current_power_w
                    - sensor.plug1_current_a
                show_header_toggle: false
                hours_to_show: 80
                refresh_interval: 60
                type: history-graph
