## NOTIFICATIONS
- alias: Irina phone away
  trigger:
    platform: state
    entity_id: device_tracker.irina
    from: 'not_home'
    to: 'home'
  action:
    - service: notify.op6_join
      data:
        message: 'elin left the house'
        title: 'elin left the house'

#fan.xiaomi_air_purifier_2s_1
- alias: Turn OFF air purifier
  trigger:
    platform: numeric_state
    entity_id: sensor.mi_1_sensor_aqi
    value_template: "{{ states('sensor.mi_1_sensor_aqi') | int }}"
    below: 20
    above: -1
    for:
      minutes: 10
  action:
    - service: xiaomi_miio.fan_set_favorite_level
      entity_id: fan.xiaomi_air_purifier_2s_1
      data:
        level: 0
    - service: fan.turn_off
      entity_id: fan.xiaomi_air_purifier_2s_1

- alias: Turn ON air purifier (not quiet)
  trigger:
    platform: numeric_state
    entity_id: sensor.mi_1_sensor_aqi
    value_template: "{{ states('sensor.mi_1_sensor_aqi') | int }}"
    above: 21
    below: 99999
    for:
      minutes: 5
  condition:
    - condition: time
      after: '9:00:00'
      before: '22:00:00'
  action:
    - service: fan.turn_on
      entity_id: fan.xiaomi_air_purifier_2s_1
    - service: fan.set_speed
      entity_id: fan.xiaomi_air_purifier_2s_1
      data:
        speed: favorite
    - service: xiaomi_miio.fan_set_favorite_level
      entity_id: fan.xiaomi_air_purifier_2s_1
      data_template:
        level: >
            {% if states('sensor.mi_1_sensor_aqi') | int > 80 %}
              14
            {% elif states('sensor.mi_1_sensor_aqi') | int > 40 %}
              10
            {% elif states('sensor.mi_1_sensor_aqi') | int > 20 %}
              7
            {% else %}
              0
            {% endif %}

- alias: Turn ON air purifier (quiet)
  trigger:
    platform: numeric_state
    entity_id: sensor.mi_1_sensor_aqi
    value_template: "{{ states('sensor.mi_1_sensor_aqi') | int }}"
    above: 21
    below: 99999
    for:
      minutes: 5
  condition:
    - condition: time
      after: '22:01:00'
      before: '8:59:00'
  action:
    - service: fan.turn_on
      entity_id: fan.xiaomi_air_purifier_2s_1
    - service: fan.set_speed
      entity_id: fan.xiaomi_air_purifier_2s_1
      data:
        speed: silent
    - service: xiaomi_miio.fan_set_favorite_level
      entity_id: fan.xiaomi_air_purifier_2s_1
      data:
        level: 0

- alias: Turn ON air purifier (quiet - was noisy)
  trigger:
    platform: numeric_state
    entity_id: sensor.mi_1_sensor_favorite_level
    value_template: "{{ states('sensor.mi_1_sensor_favorite_level') | int }}"
    above: 0
  condition:
    - condition: time
      after: '22:01:00'
      before: '8:59:00'
  action:
    - service: fan.set_speed
      entity_id: fan.xiaomi_air_purifier_2s_1
      data:
        speed: silent
    - service: xiaomi_miio.fan_set_favorite_level
      entity_id: fan.xiaomi_air_purifier_2s_1
      data:
        level: 0
